language: java
jdk:
  - oraclejdk8
before_install:
  - mvn license:format
  - mvn versions:use-latest-releases
  - mvn scm:checkin "-Dmessage=updating license and dependencies”
before_script:
  - mvn versions:set -DnewVersion=1.$TRAVIS_BUILD_NUMBER
after_script:
  - mvn scm:tag